version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: todo-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  todo-node-app:
    build: .
    container_name: todo-app
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/todo_app_db
    volumes:
      - .:/app
    command: npm start

volumes:
  mongo_data:
